apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
  labels:
    app: rag-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
        - name: rag-backend
          # For local Minikube builds use image: rag-backend:latest
          # For registry use: ghcr.io/YOUR_GH_USER/rag-backend:latest
          image: rag-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: FAISS_INDEX_PATH
              value: "/data/faiss_index.pkl"
          volumeMounts:
            - name: faiss-volume
              mountPath: /data
      volumes:
        - name: faiss-volume
          hostPath:
            path: /tmp/faiss   # local host path; minikube will see this
            type: DirectoryOrCreate
