name: Deploy Backend to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      - name: Push to Hugging Face Space
        run: |
          cd backend
          git init
          git remote add origin https://huggingface.co/spaces/<username>/<backend-space>
          git add .
          git commit -m "Deploy backend"
          git push origin main --force
